### PR TITLE
Update page.md

### PR DESCRIPTION
**Pull request by userkace**
added my instance and extension installation for both firefox and chromium browsers

### CODE REVIEW

**Comment by erynith** [comment]
ur instance doesn't have a default proxy

u could atleast make one on cloudflare and call it a day 🤷‍♂️

**Comment by userkace** [comment]
[config.js](https://github.com/userkace/film.kace.dev/blob/main/config.js) clearly has a proxy...

**Comment by erynith** [comment]
the /admin route does not show it

**Comment by userkace** [comment]
image
and requests are going through my proxy

**Comment by erynith** [comment]
added instance

**Pull request closed without merging**
